    

GET http://localhost:3000/posts
Authorization: Bearer
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjA4MjM0MDN9.bUKS90jQYSwvfjFwP11XdXg-0CUWAPsTRvvzEvmHP9g

###

POST http://localhost:3000/users 
Content-Type: application/json

{
    "name": "Kyle", "password": "password"
}

###

POST http://localhost:3000/users/login 
Content-Type: application/json

{
    "name": "Kyle", "password": "password"

}


